### PR TITLE
Use mentioned_by_self_text correctly

### PR DESCRIPTION
**Pull request by datitisev**
This uses `mentioned_by_self_text` correctly... I think.

All I did was make the part that adds `_self` to use `repliers` instead of `replies`, because `repliers` has no duplicates and it sorts the session user to be in index `0`.

I attach some images... with the French language, because there's really no difference in English.

Closes flarum/core#621

---

_username and You replied to this_
img

_datitisev replied to this_
img

_You replied to this_
img

### CODE REVIEW

**Comment by tobscure** [comment]
Looks good, apart from the dist.js issue, similar to flarum/flarum-ext-mentions#25...

**Comment by datitisev** [comment]
@tobscure Done! \:D

**Comment by tobscure** [comment]
Thanks!

**Comment by datitisev** [comment]
No problem! :)

**Pull request merged**
