### PR TITLE
fixed linking using urlGenerator for AddPostMentionsFormatter

### PR DESCRIPTION
**Pull request by Luceos**
ready for merging, after the PR from core is done:

https://github.com/flarum/core/pull/518

### CODE REVIEW

**Comment by tobscure** [comment]
Relevant: https://github.com/flarum/core/issues/123

**Comment by Luceos** [comment]
This is done see https://github.com/flarum/core/pull/518 and #123

**Comment by tobscure** [comment]
There are two stages of text formatting:

1. When the post is saved, the raw content is **parsed** into XML and stored in the database.
2. When the post needs to be rendered, the XML is **rendered** into HTML.

One of the benefits of having these split up is that we can put off stuff like URL generation until the **rendering** step. That way, if the forum's URL structure ever changes, mentions that have already been parsed won't break!

This PR is generating the URLs on the **parsing** step, which is not what we want.

**Comment by Luceos** [comment]
@tobscure I'm still trying to figure out the eco system. And if I compare both files (and their results in my database):

```
<r><p><POSTMENTION id="21" username="luceos">@luceos#21</POSTMENTION></p> 

<p><USERMENTION id="1" url="https://laravel.today/u/luceos" username="luceos">@luceos</USERMENTION></p> </r>
```

The postmention works, but the usermention does not. I however do not see the difference in the code, could you point me out how the usermention parses the url earlier? There does seem to be coming in a call on `render` but I'm not sure where it originates from.

**Comment by tobscure** [comment]
Closing as this is very outdated. It's been half fixed in the recent months – we now use the URL generator to get the base URL, but we still append the discussion/user ID onto the end of that which isn't ideal. The solution is here: https://github.com/s9e/TextFormatter/issues/23

**Comment by Luceos** [comment]
Didn't even remember opening this one. So :+1:

**Pull request closed without merging**
