### PR TITLE
Show quote button when post text is selected

### PR DESCRIPTION
**Pull request by sijad**
Fixes flarum/core#320
Let me know if you think it's dirty

### CODE REVIEW

**Comment by franzliedke** [comment]
Wow, this looks awesome, great job!
I'll give it a thorough review now.

I know I suggested using a library in the ticket, but seeing its size, it's better to just implement the bit we need ourselves. Which you did, great. :)

**Comment by tobscure** [comment]
Looks very good, couple of problems:

* Translation key should be suffixed with `_button` (i.e. `flarum-mentions.forum.post.quote_button`). Also need a PR to flarum-ext-english please
* The quote button isn't showing when you highlight over styled text.
* Page scrolls to the top when you click the quote button.

**Comment by sijad** [comment]
@tobscure thanks for review, they have been fixed

```diff
diff --git a/js/forum/src/addPostQuoteButton.js b/js/forum/src/addPostQuoteButton.js
index 27b59b4..231088d 100644
--- a/js/forum/src/addPostQuoteButton.js
+++ b/js/forum/src/addPostQuoteButton.js
@@ -2,7 +2,6 @@ import { extend } from 'flarum/extend';
 import CommentPost from 'flarum/components/CommentPost';
 
 import PostQuoteButton from 'flarum/mentions/components/PostQuoteButton';
-import reply from 'flarum/mentions/utils/reply';
 
 export default function addPostQuoteButton() {
   extend(CommentPost.prototype, 'config', function(original, isInitialized) {
@@ -28,6 +27,7 @@ export default function addPostQuoteButton() {
           if (parent.nodeType != 1) {
               return parent.parentNode;
           }
+          return parent;
       }
     }
 
diff --git a/js/forum/src/components/PostQuoteButton.js b/js/forum/src/components/PostQuoteButton.js
index e27f827..d763993 100644
--- a/js/forum/src/components/PostQuoteButton.js
+++ b/js/forum/src/components/PostQuoteButton.js
@@ -9,10 +9,10 @@ export default class PostQuoteButton extends Component {
   }
 
   view() {
-    const text = app.translator.trans('flarum-mentions.forum.post.quote');
+    const text = app.translator.trans('flarum-mentions.forum.post.quote_button');
     return (
       <ul className="Dropdown-menu PostQuoteButton fade">
-        <li><a href="#" onclick={() => reply(this.post, this.props.quote)}>{text}</a></li>
+        <li><button onclick={() => reply(this.post, this.props.quote)}>{text}</button></li>
       </ul>
     );
   }
@@ -21,15 +21,17 @@ export default class PostQuoteButton extends Component {
     const $this = this.$();
 
     // Show button middle of clicked position.
-    offset = $this.outerHeight() + 25;
+    const offset = $this.outerHeight() + 25;
 
     // If the button goes off the top of the viewport, reposition
     // it to be below the line.
     if (top - offset < $(window).scrollTop() + $('#header').outerHeight()) {
-      offset = -10;
+      top -= 10;
+    } else {
+      top -= offset;
     }
+
     left -= $this.outerWidth() / 2;
-    top -= offset;
     $this.show()
       .css('top', top)
       .css('left', left);
```

**Comment by tobscure** [comment]
Thanks so much @sijad! Merged with a bunch of changes:

- Position quote button just above the start of the text selection (to prevent overlapping the selected text)
- Restyled as a button with an icon
- Allow selection across multiple paragraphs

**Comment by franzliedke** [comment]
Regarding the positioning: Is there a way to detect where the user stopped dragging (must be either at the end of the selection or the beginning) and make the tooltip appear there?

**Comment by tobscure** [comment]
That was the behaviour that @sijad had implemented, but the button often ended up displaying on top of the text you had just selected. We can look at refining this though.

**Comment by sijad** [comment]
@tobscure @franzliedke I didn't spend much time on that but https://yabwe.github.io/medium-editor/ can be an example of showing button in right place

**Pull request closed without merging**
